### ISSUE TITLE
New feature for pyodesys.Result

### ISSUE THREAD

**Issue by ProfLeao** [bjodah/pyodesys#125]
Hi everyone. 

I'm actually working with `chempy.kinetics.ode.get_odesys` integrations, and I've been feeling lackage of attribute to get compound names in `pyodesys.Result`. Of course I can get then using something like `getattr(odesys,'names')`, but what do you think about a unique attribute for it?

With a feature like this, the user can manipulate data to create a personalized plot in an easier way, or use another plot library instead of matplotlib, for example.

**Comment by bjodah** [comment]
I think that a names attribute sounds like a reasonable feature to have, so I'd be open to a PR. :-)

**Comment by ProfLeao** [comment]
Yeah! I got this.

**Comment by ProfLeao** [comment]
Done!
