### ISSUE TITLE
JOSS: Missing Contributing Guidelines

### ISSUE THREAD

**Issue by arghdos** [bjodah/pyodesys#69]
@bjodah the only remaining issue for the [JOSS review](https://github.com/openjournals/joss-reviews/issues/490) is a missing contribution guidlines:

> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

See here for [an example](https://gist.github.com/PurpleBooth/b24679402957c63ec426)

**Comment by bjodah** [comment]
Thanks. Yes, I should probably have written a bit more than a single sentence in the readme. I'm adressing this in gh-70.

**Comment by arghdos** [comment]
@bjodah looks good!  Sorry for the delay, was out of town.

**Comment by bjodah** [comment]
No worries, hope you enjoyed the holidays. I merged gh-70.
